export interface HookTemplate {
  id: string;
  category: 'curiosity' | 'mistake' | 'wish_i_knew' | 'secret' | 'story' | 'challenge' | 'relatable' | 'shortcut' | 'controversy' | 'pattern_interrupt';
  title: string;
  template: string;
  example: string;
  whyItWorks: string;
}

export const VIRAL_HOOK_LIBRARY: HookTemplate[] = [
  // 1. "WISH I KNEW" & REGRET HOOKS (10)
  {
    id: 'hook-wk-1',
    category: 'wish_i_knew',
    title: 'The Early Regret Opening',
    template: 'I wish I knew this before I started [Topic]...',
    example: 'I wish I knew this before I started creating videos on TikTok...',
    whyItWorks: 'Taps into fear of missing out and saves the viewer time.',
  },
  {
    id: 'hook-wk-2',
    category: 'wish_i_knew',
    title: 'The Financial / Time Wasted Hook',
    template: 'I wasted 3 years doing [Topic] wrong until I learned this...',
    example: 'I wasted 3 years trying to grow my account wrong until I learned this simple trick.',
    whyItWorks: 'Frame your past pain as their shortcut.',
  },
  {
    id: 'hook-wk-3',
    category: 'wish_i_knew',
    title: 'The Beginner Mistake Warning',
    template: 'If you are starting [Topic] in 2026, do NOT make this mistake...',
    example: 'If you are starting a YouTube channel in 2026, do NOT make this mistake...',
    whyItWorks: 'Direct warning creates instant urgency to avoid failure.',
  },
  {
    id: 'hook-wk-4',
    category: 'wish_i_knew',
    title: 'The Hard Truth Revelation',
    template: 'Nobody told me this about [Topic] when I was a beginner...',
    example: 'Nobody told me this about editing short videos when I was a beginner...',
    whyItWorks: 'Promises insider knowledge that people normally hide.',
  },
  {
    id: 'hook-wk-5',
    category: 'wish_i_knew',
    title: 'The Expensive Lesson',
    template: 'This $1,000 lesson about [Topic] took me years to realize...',
    example: 'This $1,000 lesson about scripting videos took me 2 years to realize...',
    whyItWorks: 'High dollar/value anchor creates immediate curiosity.',
  },
  {
    id: 'hook-wk-6',
    category: 'wish_i_knew',
    title: 'The Life-Changing Realization',
    template: 'My entire view on [Topic] changed the moment I discovered this...',
    example: 'My entire view on audience retention changed the moment I discovered this...',
    whyItWorks: 'Hyped personal transformation builds immediate trust.',
  },
  {
    id: 'hook-wk-7',
    category: 'wish_i_knew',
    title: 'The Retrospective Shortcut',
    template: 'If I had to restart [Topic] from zero, here is the exact first thing I would do...',
    example: 'If I had to restart my social media from zero, here is the exact first thing I would do...',
    whyItWorks: 'People love "reset to zero" blueprint videos.',
  },
  {
    id: 'hook-wk-8',
    category: 'wish_i_knew',
    title: 'The Easier Way Guarantee',
    template: 'Stop doing [Topic] the hard way. Do this instead...',
    example: 'Stop doing video editing the hard way. Do this instead...',
    whyItWorks: 'Offers laziness-friendly efficiency.',
  },
  {
    id: 'hook-wk-9',
    category: 'wish_i_knew',
    title: 'The Myth Buster',
    template: 'Everything you were taught about [Topic] is actually wrong...',
    example: 'Everything you were taught about posting times is actually wrong...',
    whyItWorks: 'Challenges existing belief systems.',
  },
  {
    id: 'hook-wk-10',
    category: 'wish_i_knew',
    title: 'The Unspoken Reality',
    template: 'The dark truth about [Topic] that nobody wants to speak about...',
    example: 'The dark truth about going viral that nobody wants to speak about...',
    whyItWorks: 'Dramatic tone commands immediate attention.',
  },

  // 2. PATTERN INTERRUPT & "STOP SCROLLING" HOOKS (10)
  {
    id: 'hook-pi-1',
    category: 'pattern_interrupt',
    title: 'Direct Screen Callout',
    template: 'Stop scrolling if you care about [Topic]!',
    example: 'Stop scrolling if you care about growing your business online!',
    whyItWorks: 'Breaks passive scrolling trance by speaking directly to the action.',
  },
  {
    id: 'hook-pi-2',
    category: 'pattern_interrupt',
    title: 'The Hold On / Wait Moment',
    template: 'Wait! Don’t swipe away until you hear this 5-second fact...',
    example: 'Wait! Don’t swipe away until you hear this 5-second trick...',
    whyItWorks: 'Creates a mini time-bound challenge (5 seconds).',
  },
  {
    id: 'hook-pi-3',
    category: 'pattern_interrupt',
    title: 'The Confusion Callout',
    template: 'Put your phone down for 10 seconds and listen to this...',
    example: 'Put your phone down for 10 seconds and listen to this hook secret...',
    whyItWorks: 'Unexpected instruction interrupts muscle memory.',
  },
  {
    id: 'hook-pi-4',
    category: 'pattern_interrupt',
    title: 'The High Voltage Warning',
    template: 'If you watch one video today about [Topic], make it this one...',
    example: 'If you watch one video today about video editing, make it this one...',
    whyItWorks: 'Frames content as essential priority viewing.',
  },
  {
    id: 'hook-pi-5',
    category: 'pattern_interrupt',
    title: 'The Audience Targeter',
    template: 'Attention [Audience Type]! This message is specifically for you...',
    example: 'Attention content creators! This message is specifically for you...',
    whyItWorks: 'Self-selection makes targeted viewers feel personally addressed.',
  },
  {
    id: 'hook-pi-6',
    category: 'pattern_interrupt',
    title: 'The Visual Disruption',
    template: 'Delete your [App/Tool] right now if you are still doing this...',
    example: 'Delete your old editing app right now if you are still doing this...',
    whyItWorks: 'Extreme action word ("Delete") creates shock value.',
  },
  {
    id: 'hook-pi-7',
    category: 'pattern_interrupt',
    title: 'The Instant Freeze',
    template: 'Freeze! Before you post your next video, check this single detail...',
    example: 'Freeze! Before you post your next reel, check this single detail...',
    whyItWorks: 'One word command halts thumb movement.',
  },
  {
    id: 'hook-pi-8',
    category: 'pattern_interrupt',
    title: 'The Whispered Secret',
    template: 'I am only going to say this once, so save this video now...',
    example: 'I am only going to say this once, so save this video right now...',
    whyItWorks: 'Scarcity + immediate bookmark trigger.',
  },
  {
    id: 'hook-pi-9',
    category: 'pattern_interrupt',
    title: 'The Direct Interruption',
    template: 'I promise this 15-second tip will save you hours of work...',
    example: 'I promise this 15-second tip will save you hours of work this week...',
    whyItWorks: 'Calculated value proposition with low time investment.',
  },
  {
    id: 'hook-pi-10',
    category: 'pattern_interrupt',
    title: 'The Uncomfortable Question',
    template: 'Why is no one talking about what happened to [Topic] recently?',
    example: 'Why is no one talking about what happened to TikTok views recently?',
    whyItWorks: 'Spurs paranoia and curiosity simultaneously.',
  },

  // 3. MISTAKE & WARNING HOOKS (10)
  {
    id: 'hook-m-1',
    category: 'mistake',
    title: 'The 3 Big Mistakes',
    template: '3 huge mistakes you are making with [Topic] without knowing it...',
    example: '3 huge mistakes you are making with your opening hooks without knowing it...',
    whyItWorks: 'Quantified errors create self-doubt.',
  },
  {
    id: 'hook-m-2',
    category: 'mistake',
    title: 'The Single Ruining Habit',
    template: 'This one small habit is completely destroying your [Desired Outcome]...',
    example: 'This one small habit is completely destroying your video retention...',
    whyItWorks: 'Identifies a hidden bottleneck.',
  },
  {
    id: 'hook-m-3',
    category: 'mistake',
    title: 'The Immediate Quit Hook',
    template: 'If you are doing [Action], STOP immediately...',
    example: 'If you are opening your videos with "Hey guys", STOP immediately...',
    whyItWorks: 'Polars opinion and demands explanation.',
  },
  {
    id: 'hook-m-4',
    category: 'mistake',
    title: 'The Costly Blunder',
    template: 'Why 95% of people fail at [Topic] in their first 30 days...',
    example: 'Why 95% of creators fail at short-form video in their first 30 days...',
    whyItWorks: 'High failure statistic triggers fear of being in the majority that fails.',
  },
  {
    id: 'hook-m-5',
    category: 'mistake',
    title: 'The Amateur Red Flag',
    template: 'How to spot an amateur in [Topic] in under 3 seconds...',
    example: 'How to spot an amateur video creator in under 3 seconds...',
    whyItWorks: 'Ego preservation—nobody wants to look like an amateur.',
  },
  {
    id: 'hook-m-6',
    category: 'mistake',
    title: 'The Hidden Trap',
    template: 'You think you are saving time on [Topic], but you are actually making it worse...',
    example: 'You think you are saving time with fast cuts, but you are actually ruining your flow...',
    whyItWorks: 'Subverts expectation of a common technique.',
  },
  {
    id: 'hook-m-7',
    category: 'mistake',
    title: 'The Biggest Lie',
    template: 'The biggest lie you were told about [Topic]...',
    example: 'The biggest lie you were told about social media algorithms...',
    whyItWorks: 'Exposes authority figures or advice as misleading.',
  },
  {
    id: 'hook-m-8',
    category: 'mistake',
    title: 'The Rookie Error',
    template: 'Are you still doing [Topic] like it is 2020? Here is what changed...',
    example: 'Are you still editing videos like it is 2020? Here is what changed...',
    whyItWorks: 'Triggers FOMO regarding outdated methods.',
  },
  {
    id: 'hook-m-9',
    category: 'mistake',
    title: 'The Silent Viewer Killer',
    template: 'The main reason people swipe away from your [Topic] within 2 seconds...',
    example: 'The main reason people swipe away from your videos within 2 seconds...',
    whyItWorks: 'Solves the exact pain point the creator is facing.',
  },
  {
    id: 'hook-m-10',
    category: 'mistake',
    title: 'The Common Misconception',
    template: 'Stop assuming [Topic] requires [Misconception]...',
    example: 'Stop assuming going viral requires expensive camera equipment...',
    whyItWorks: 'Lowers barriers to entry.',
  },

  // 4. SECRET & HACK HOOKS (10)
  {
    id: 'hook-s-1',
    category: 'secret',
    title: 'The Gatekept Industry Secret',
    template: 'The secret tool that top [Industry/Creators] use to [Benefit]...',
    example: 'The secret tool that top creators use to double their views...',
    whyItWorks: 'Promises forbidden or insider leverage.',
  },
  {
    id: 'hook-s-2',
    category: 'secret',
    title: 'The Hidden Website / Feature',
    template: 'This hidden website feels illegal to know for [Topic]...',
    example: 'This hidden AI website feels illegal to know for scripting videos...',
    whyItWorks: '"Feels illegal" is a viral buzzphrase for high utility.',
  },
  {
    id: 'hook-s-3',
    category: 'secret',
    title: 'The 10-Second Hack',
    template: 'How to get [Benefit] using this 10-second hack...',
    example: 'How to get 10k views using this 10-second audio trick...',
    whyItWorks: 'High result + ultra low effort.',
  },
  {
    id: 'hook-s-4',
    category: 'secret',
    title: 'The Cheat Code',
    template: 'Here is the ultimate cheat code for [Topic] nobody shares...',
    example: 'Here is the ultimate cheat code for viral video hooks nobody shares...',
    whyItWorks: 'Uses gaming metaphor for instant gratification.',
  },
  {
    id: 'hook-s-5',
    category: 'secret',
    title: 'The Unfair Advantage',
    template: 'Give yourself an unfair advantage in [Topic] with this simple technique...',
    example: 'Give yourself an unfair advantage on TikTok with this simple technique...',
    whyItWorks: 'Competitiveness drives interest.',
  },
  {
    id: 'hook-s-6',
    category: 'secret',
    title: 'The Hidden Button',
    template: 'Most people don’t know this secret setting in [Tool/App]...',
    example: 'Most creators don’t know this secret audio setting in CapCut...',
    whyItWorks: 'Highly specific platform actionable tip.',
  },
  {
    id: 'hook-s-7',
    category: 'secret',
    title: 'The Pro Shortcut',
    template: 'How pros do [Topic] in 5 minutes while beginners spend 5 hours...',
    example: 'How pros write video scripts in 5 minutes while beginners spend 5 hours...',
    whyItWorks: 'Contrast between pro and beginner efficiency.',
  },
  {
    id: 'hook-s-8',
    category: 'secret',
    title: 'The Algorithm Loophole',
    template: 'The exact trick I used to unlock [Desired Result]...',
    example: 'The exact trick I used to unlock 100,000 extra impressions...',
    whyItWorks: 'Proof-based personal case study.',
  },
  {
    id: 'hook-s-9',
    category: 'secret',
    title: 'The Secret Formula',
    template: 'Steal my 3-step formula for effortless [Outcome]...',
    example: 'Steal my 3-step formula for effortless viral scriptwriting...',
    whyItWorks: '"Steal my formula" gives permission for quick gains.',
  },
  {
    id: 'hook-s-10',
    category: 'secret',
    title: 'The VIP Trick',
    template: 'This simple tweak boosted my [Metric] by 300%...',
    example: 'This simple hook tweak boosted my audience retention by 300%...',
    whyItWorks: 'Tangible percentage growth anchor.',
  },

  // 5. CURIOSITY GAP & QUESTION HOOKS (10)
  {
    id: 'hook-c-1',
    category: 'curiosity',
    title: 'The "What Happens When" Hook',
    template: 'Have you ever wondered what happens if you [Action]?',
    example: 'Have you ever wondered what happens if you change your first 3 seconds?',
    whyItWorks: 'Invites experiment-driven curiosity.',
  },
  {
    id: 'hook-c-2',
    category: 'curiosity',
    title: 'The Bizarre Reality',
    template: 'Why does [Common Thing] actually do [Unexpected Outcome]?',
    example: 'Why does posting shorter videos actually yield higher watch time?',
    whyItWorks: 'Counter-intuitive logic forces mind to seek resolution.',
  },
  {
    id: 'hook-c-3',
    category: 'curiosity',
    title: 'The Unsolved Mystery',
    template: 'How did this [Topic] get [Insane Result] with zero effort?',
    example: 'How did this simple 7-second video get 5 million views with zero effort?',
    whyItWorks: 'Analyzes viral outlier cases.',
  },
  {
    id: 'hook-c-4',
    category: 'curiosity',
    title: 'The Test It Yourself Hook',
    template: 'Try this simple test right now to see if your [Topic] is working...',
    example: 'Try this simple test right now to see if your video hook is strong enough...',
    whyItWorks: 'Interactive participation prompt.',
  },
  {
    id: 'hook-c-5',
    category: 'curiosity',
    title: 'The Weird Trick',
    template: 'This sounds weird, but [Action] is actually the fastest way to [Result]...',
    example: 'This sounds weird, but pausing before you talk is actually the fastest way to hook viewers...',
    whyItWorks: 'Acknowledges oddity upfront.',
  },
  {
    id: 'hook-c-6',
    category: 'curiosity',
    title: 'The Question Hook',
    template: 'What is the #1 thing holding your [Topic] back right now?',
    example: 'What is the #1 thing holding your video reach back right now?',
    whyItWorks: 'Forces viewer to diagnose their own problem.',
  },
  {
    id: 'hook-c-7',
    category: 'curiosity',
    title: 'The Paradox Hook',
    template: 'Why doing LESS of [Topic] gives you MORE [Result]...',
    example: 'Why speaking LESS in your intro gives you MORE retention...',
    whyItWorks: 'Paradoxical statement creates brain itch.',
  },
  {
    id: 'hook-c-8',
    category: 'curiosity',
    title: 'The "Is It Worth It" Hook',
    template: 'Is [Tool/Method] actually worth it or is it just hype?',
    example: 'Is using AI scriptwriters actually worth it or just hype?',
    whyItWorks: 'Unbiased review expectation.',
  },
  {
    id: 'hook-c-9',
    category: 'curiosity',
    title: 'The Crazy Experiment',
    template: 'I tried [Action] for 7 days straight. Here is what happened...',
    example: 'I posted 3 shorts a day for 7 days straight. Here is what happened...',
    whyItWorks: 'Storytelling format with clear duration.',
  },
  {
    id: 'hook-c-10',
    category: 'curiosity',
    title: 'The Hidden Cause',
    template: 'There is a reason why your [Topic] isn’t working, and it’s not what you think...',
    example: 'There is a reason why your videos aren’t blowing up, and it’s not what you think...',
    whyItWorks: 'Subverts common blame targets.',
  },

  // 6. SHORTCUT & HOW-TO HOOKS (10)
  {
    id: 'hook-sc-1',
    category: 'shortcut',
    title: 'The Step-by-Step Blueprint',
    template: 'How to [Achieve Goal] in 3 simple steps even if you are a total beginner...',
    example: 'How to hook viewers in 3 simple steps even if you are a total beginner...',
    whyItWorks: 'Simplifies complex skills.',
  },
  {
    id: 'hook-sc-2',
    category: 'shortcut',
    title: 'The Lazy Way',
    template: 'The absolute easiest way to [Outcome] without spending money...',
    example: 'The absolute easiest way to edit viral videos without spending money...',
    whyItWorks: 'Zero cost + ease of execution.',
  },
  {
    id: 'hook-sc-3',
    category: 'shortcut',
    title: 'The 60-Second Tutorial',
    template: 'Everything you need to master [Topic] in under 60 seconds...',
    example: 'Everything you need to master lighting in under 60 seconds...',
    whyItWorks: 'Clear time boundary promises high density of value.',
  },
  {
    id: 'hook-sc-4',
    category: 'shortcut',
    title: 'The Exact Template',
    template: 'Use this exact script template for your next [Topic] video...',
    example: 'Use this exact script template for your next product review video...',
    whyItWorks: 'Done-for-you copyable resource.',
  },
  {
    id: 'hook-sc-5',
    category: 'shortcut',
    title: 'The Rapid Fix',
    template: 'Fix your bad [Problem] in under 2 minutes with this quick fix...',
    example: 'Fix your video pacing in under 2 minutes with this quick edit...',
    whyItWorks: 'Fast turnaround time for annoying issues.',
  },
  {
    id: 'hook-sc-6',
    category: 'shortcut',
    title: 'The Zero-To-Hero',
    template: 'From 0 to [Metric]: Here is the exact framework I used...',
    example: 'From 0 to 50k followers: Here is the exact framework I used...',
    whyItWorks: 'Aspirational benchmark.',
  },
  {
    id: 'hook-sc-7',
    category: 'shortcut',
    title: 'The Beginner Checklist',
    template: 'Save this checklist before making your next [Topic]...',
    example: 'Save this checklist before posting your next short-form video...',
    whyItWorks: 'High bookmark utility metric for platform algorithm.',
  },
  {
    id: 'hook-sc-8',
    category: 'shortcut',
    title: 'The Smart Hack',
    template: 'Work smarter, not harder: Do this instead of [Tedious Task]...',
    example: 'Work smarter, not harder: Do this instead of manually typing subtitles...',
    whyItWorks: 'Relieves friction in creator workflow.',
  },
  {
    id: 'hook-sc-9',
    category: 'shortcut',
    title: 'The Ultimate Guide',
    template: 'The only [Topic] guide you will ever need in 2026...',
    example: 'The only video pacing guide you will ever need in 2026...',
    whyItWorks: 'Definitive authority claim.',
  },
  {
    id: 'hook-sc-10',
    category: 'shortcut',
    title: 'The 1-Click Solution',
    template: 'How to automate [Task] so you never have to do it manually again...',
    example: 'How to automate your video captions so you never do it manually again...',
    whyItWorks: 'Automation appeal.',
  },

  // 7. RELATABLE & CONFESSION HOOKS (10)
  {
    id: 'hook-r-1',
    category: 'relatable',
    title: 'The Shared Frustration',
    template: 'Is it just me, or is everyone else tired of [Frustrating Problem]?',
    example: 'Is it just me, or is everyone else tired of low views despite high effort?',
    whyItWorks: 'Builds instant community empathy.',
  },
  {
    id: 'hook-r-2',
    category: 'relatable',
    title: 'The Honest Admission',
    template: 'I am going to be 100% honest with you about [Topic]...',
    example: 'I am going to be 100% honest with you about how hard video growth is...',
    whyItWorks: 'Authenticity breaks corporate polished tone.',
  },
  {
    id: 'hook-r-3',
    category: 'relatable',
    title: 'The Relatable Struggle',
    template: 'If you struggle with [Problem], you are not alone. Here is the fix...',
    example: 'If you struggle with coming up with video ideas, you are not alone...',
    whyItWorks: 'Normalizes failure then provides relief.',
  },
  {
    id: 'hook-r-4',
    category: 'relatable',
    title: 'The Uncomfortable Truth',
    template: 'We all pretend that [Common Action] works, but we know it doesn’t...',
    example: 'We all pretend that posting 5 times a day works, but we know it doesn’t...',
    whyItWorks: 'Calls out shared unspoken skepticism.',
  },
  {
    id: 'hook-r-5',
    category: 'relatable',
    title: 'The Personal Story',
    template: 'I almost gave up on [Topic] until this one moment happened...',
    example: 'I almost gave up on creating content until this one moment happened...',
    whyItWorks: 'Vulnerability hooks emotional investment.',
  },
  {
    id: 'hook-r-6',
    category: 'relatable',
    title: 'The Daily Routine Reality',
    template: 'Real talk: This is what actually happens when you try [Topic]...',
    example: 'Real talk: This is what actually happens when you try to record daily...',
    whyItWorks: 'Behind-the-scenes grounded feel.',
  },
  {
    id: 'hook-r-7',
    category: 'relatable',
    title: 'The Calling Out Casuals',
    template: 'Raise your hand if you have ever spent 2 hours doing [Task] for zero views...',
    example: 'Raise your hand if you have ever spent 2 hours editing for 50 views...',
    whyItWorks: 'Hyper-relatable pain point.',
  },
  {
    id: 'hook-r-8',
    category: 'relatable',
    title: 'The "Am I Crazy?" Hook',
    template: 'Am I crazy or is [Topic] getting way harder than it used to be?',
    example: 'Am I crazy or is getting retention on Instagram getting harder?',
    whyItWorks: 'Validates viewer suspicion.',
  },
  {
    id: 'hook-r-9',
    category: 'relatable',
    title: 'The Turning Point',
    template: 'The day I stopped doing [Bad Habit] was the day my [Metric] exploded...',
    example: 'The day I stopped making long intros was the day my views exploded...',
    whyItWorks: 'Clear before/after pivot story.',
  },
  {
    id: 'hook-r-10',
    category: 'relatable',
    title: 'The Real Cost',
    template: 'What no one tells you about the burnout of [Topic]...',
    example: 'What no one tells you about the burnout of content creation...',
    whyItWorks: 'Deep emotional empathy.',
  },

  // 8. CONTROVERSY & HOT TAKE HOOKS (10)
  {
    id: 'hook-ct-1',
    category: 'controversy',
    title: 'The Unpopular Opinion',
    template: 'Unpopular opinion: [Common Wisdom] is completely overrated...',
    example: 'Unpopular opinion: High resolution cameras are completely overrated for shorts...',
    whyItWorks: 'Spurs debate in comments section.',
  },
  {
    id: 'hook-ct-2',
    category: 'controversy',
    title: 'The Bold Claim',
    template: 'I am going to get hate for this, but [Bold Statement]...',
    example: 'I am going to get hate for this, but hashtags don’t matter anymore...',
    whyItWorks: 'Anticipated backlash builds tension.',
  },
  {
    id: 'hook-ct-3',
    category: 'controversy',
    title: 'The Call Out',
    template: 'Stop listening to gurus who tell you to [Bad Advice]...',
    example: 'Stop listening to gurus who tell you to post 10 times a day...',
    whyItWorks: 'Us vs. Them framing.',
  },
  {
    id: 'hook-ct-4',
    category: 'controversy',
    title: 'The Industry Callout',
    template: '[Popular Tool/Trend] is a total waste of money and here is why...',
    example: 'Expensive ring lights are a total waste of money and here is why...',
    whyItWorks: 'Protects viewer wallet from hype.',
  },
  {
    id: 'hook-ct-5',
    category: 'controversy',
    title: 'The Rejection of Norms',
    template: 'Why I refuse to use [Popular Trend] anymore...',
    example: 'Why I refuse to use trending sounds anymore...',
    whyItWorks: 'Contrarian stance stands out.',
  },
  {
    id: 'hook-ct-6',
    category: 'controversy',
    title: 'The Direct Debate',
    template: 'Is [Option A] better than [Option B]? Let’s settle this once and for all...',
    example: 'Are TikTok Reels better than YouTube Shorts? Let’s settle this...',
    whyItWorks: 'Triggers tribal loyalty.',
  },
  {
    id: 'hook-ct-7',
    category: 'controversy',
    title: 'The Brutal Audit',
    template: 'Your [Topic] isn’t failing because of the algorithm. It’s failing because...',
    example: 'Your video isn’t failing because of the algorithm. It’s failing because of your hook...',
    whyItWorks: 'Tough love reality check.',
  },
  {
    id: 'hook-ct-8',
    category: 'controversy',
    title: 'The Shocking Statistic',
    template: 'Did you know that 80% of [Audience] will ignore [Topic] because of this?',
    example: 'Did you know that 80% of viewers swipe away if you take 3 seconds to speak?',
    whyItWorks: 'Hard metrics command authority.',
  },
  {
    id: 'hook-ct-9',
    category: 'controversy',
    title: 'The Overhyped Trend',
    template: 'Why everyone is wrong about [Current Trend]...',
    example: 'Why everyone is wrong about AI video generators...',
    whyItWorks: 'Rides wave of trending topics with critical lens.',
  },
  {
    id: 'hook-ct-10',
    category: 'controversy',
    title: 'The Hard Pill to Swallow',
    template: 'The uncomfortable reason nobody is engaging with your [Topic]...',
    example: 'The uncomfortable reason nobody is sharing your content...',
    whyItWorks: 'Direct confrontation forces curiosity.',
  },

  // 9. HIGH-VALUE & MONEY/GROWTH HOOKS (10)
  {
    id: 'hook-v-1',
    category: 'secret',
    title: 'The High ROI Habit',
    template: 'Doing this 1 thing every day brought me [Massive Result]...',
    example: 'Doing this 1 script tweak every day brought me 500k views...',
    whyItWorks: 'Single high-impact leverage point.',
  },
  {
    id: 'hook-v-2',
    category: 'wish_i_knew',
    title: 'The Free Tool Alternative',
    template: 'Don’t pay for [Paid Tool]. Use this free alternative instead...',
    example: 'Don’t pay for pro teleprompters. Use this free browser app instead...',
    whyItWorks: 'Direct savings offer.',
  },
  {
    id: 'hook-v-3',
    category: 'shortcut',
    title: 'The Growth Hack',
    template: 'How to double your [Metric] without creating more content...',
    example: 'How to double your view count without creating more videos...',
    whyItWorks: 'Leveraging existing work.',
  },
  {
    id: 'hook-v-4',
    category: 'secret',
    title: 'The Asset Steal',
    template: 'I built a list of [Resources/Tips] so you don’t have to...',
    example: 'I built a list of 100 viral hook ideas so you don’t have to...',
    whyItWorks: 'Consolidated effort provided on silver platter.',
  },
  {
    id: 'hook-v-5',
    category: 'pattern_interrupt',
    title: 'The Instant Upgrade',
    template: 'Upgrade your [Topic] from basic to pro in 30 seconds...',
    example: 'Upgrade your video audio from basic to studio level in 30 seconds...',
    whyItWorks: 'Quick quality transformation.',
  },
  {
    id: 'hook-v-6',
    category: 'wish_i_knew',
    title: 'The Zero Budget Win',
    template: 'How to look like a $10k production on a $0 budget...',
    example: 'How to make your videos look like a $10k production on a $0 budget...',
    whyItWorks: 'Extreme value to cost ratio.',
  },
  {
    id: 'hook-v-7',
    category: 'shortcut',
    title: 'The Fast-Track Method',
    template: 'The fastest way to reach [Goal] in 2026...',
    example: 'The fastest way to reach 10,000 subscribers in 2026...',
    whyItWorks: 'Urgent speed expectation.',
  },
  {
    id: 'hook-v-8',
    category: 'secret',
    title: 'The Golden Rule',
    template: 'The #1 golden rule of [Topic] that changed my career...',
    example: 'The #1 golden rule of video pacing that changed my channel...',
    whyItWorks: 'Foundational principle framing.',
  },
  {
    id: 'hook-v-9',
    category: 'mistake',
    title: 'The Waste of Time',
    template: 'Stop wasting hours on [Minor Thing]. Focus on this instead...',
    example: 'Stop wasting hours on color grading. Focus on your hook instead...',
    whyItWorks: 'Directs priority to what actually matters.',
  },
  {
    id: 'hook-v-10',
    category: 'relatable',
    title: 'The Result Reveal',
    template: 'This simple trick took me from [Low Metric] to [High Metric] in 14 days...',
    example: 'This simple trick took my completion rate from 20% to 75% in 14 days...',
    whyItWorks: 'Time-bound proof curve.',
  },

  // 10. CATEGORY EXTENSIONS TO REACH ~100 HOOKS (30 ADDITIONAL UNIQUE VARIATIONS)
  {
    id: 'hook-ex-1',
    category: 'wish_i_knew',
    title: 'The Beginner Pitfall',
    template: 'If I started over today, I would completely ignore [Topic]...',
    example: 'If I started over today, I would completely ignore fancy camera gear...',
    whyItWorks: 'Saves newcomer overwhelm.',
  },
  {
    id: 'hook-ex-2',
    category: 'pattern_interrupt',
    title: 'The Screeching Halt',
    template: 'Stop whatever you are doing and save this video right now!',
    example: 'Stop whatever you are doing and save this video right now for later!',
    whyItWorks: 'Direct command format.',
  },
  {
    id: 'hook-ex-3',
    category: 'mistake',
    title: 'The Dumbest Mistake',
    template: 'The single dumbest mistake you can make when posting [Topic]...',
    example: 'The single dumbest mistake you can make when posting short reels...',
    whyItWorks: 'Strong emotional trigger.',
  },
  {
    id: 'hook-ex-4',
    category: 'secret',
    title: 'The Cheat Code 2.0',
    template: 'Here is how top creators trick the algorithm into pushing their content...',
    example: 'Here is how top creators trick the algorithm into pushing their shorts...',
    whyItWorks: 'Outsmarting the platform.',
  },
  {
    id: 'hook-ex-5',
    category: 'curiosity',
    title: 'The Secret Discovered',
    template: 'I accidentally discovered the secret to [Desired Outcome]...',
    example: 'I accidentally discovered the secret to 100% video completion rate...',
    whyItWorks: 'Accidental discovery feels genuine.',
  },
  {
    id: 'hook-ex-6',
    category: 'shortcut',
    title: 'The 3-Word Fix',
    template: 'Change these 3 words in your video opening to 10x your views...',
    example: 'Change these 3 words in your opening sentence to 10x your retention...',
    whyItWorks: 'Ultra specific micro adjustment.',
  },
  {
    id: 'hook-ex-7',
    category: 'relatable',
    title: 'The Embarrassing Past',
    template: 'Looking back at my old [Topic] videos makes me cringe, here’s why...',
    example: 'Looking back at my old video hooks makes me cringe, here is why...',
    whyItWorks: 'Relatable growth journey.',
  },
  {
    id: 'hook-ex-8',
    category: 'controversy',
    title: 'The Unpopular Strategy',
    template: 'Why doing the OPPOSITE of what everyone else does actually works...',
    example: 'Why posting less frequently actually increased my video views...',
    whyItWorks: 'Contrarian competitive edge.',
  },
  {
    id: 'hook-ex-9',
    category: 'wish_i_knew',
    title: 'The Time Saver',
    template: 'I wish someone gave me this 1-page template 5 years ago...',
    example: 'I wish someone gave me this 1-page script template 5 years ago...',
    whyItWorks: 'Condenses years into a single asset.',
  },
  {
    id: 'hook-ex-10',
    category: 'pattern_interrupt',
    title: 'The Urgent Reminder',
    template: 'Before you record your next video, watch this first!',
    example: 'Before you record your next reel, watch this 15-second tip first!',
    whyItWorks: 'Pre-flight check mindset.',
  },
  {
    id: 'hook-ex-11',
    category: 'secret',
    title: 'The Hidden Feature',
    template: 'This hidden tool turns boring text into high-converting scripts...',
    example: 'This hidden tool turns boring text into high-converting video hooks...',
    whyItWorks: 'Direct utility for video creators.',
  },
  {
    id: 'hook-ex-12',
    category: 'curiosity',
    title: 'The Unexpected Question',
    template: 'What if everything you know about [Topic] is a total lie?',
    example: 'What if everything you know about video SEO is a total lie?',
    whyItWorks: 'Existential doubt for creators.',
  },
  {
    id: 'hook-ex-13',
    category: 'shortcut',
    title: 'The 5-Second Upgrade',
    template: 'The 5-second lighting trick that makes your video look 10x better...',
    example: 'The 5-second lighting trick that makes your video look 10x better...',
    whyItWorks: 'Instant visual gain.',
  },
  {
    id: 'hook-ex-14',
    category: 'mistake',
    title: 'The Silent Killer',
    template: 'The silent error killing your [Metric] before anyone even watches...',
    example: 'The silent error killing your view duration before anyone even watches...',
    whyItWorks: 'Unseen problem alert.',
  },
  {
    id: 'hook-ex-15',
    category: 'wish_i_knew',
    title: 'The Mindset Pivot',
    template: 'The moment I stopped caring about [X] and focused on [Y], my views doubled...',
    example: 'The moment I stopped caring about gear and focused on hooks, my views doubled...',
    whyItWorks: 'Clear prioritization guidance.',
  },
  {
    id: 'hook-ex-16',
    category: 'pattern_interrupt',
    title: 'The Direct Call Out',
    template: 'Don’t swipe! This 1 tip will fix your video retention forever...',
    example: 'Don’t swipe! This 1 tip will fix your video retention forever...',
    whyItWorks: 'High conviction statement.',
  },
  {
    id: 'hook-ex-17',
    category: 'controversy',
    title: 'The Myth Destruction',
    template: 'Posting at 6 PM is NOT helping your video. Here is why...',
    example: 'Posting at 6 PM is NOT helping your video reach. Here is why...',
    whyItWorks: 'Debunks popular internet myth.',
  },
  {
    id: 'hook-ex-18',
    category: 'shortcut',
    title: 'The One-Minute Fix',
    template: 'Fix your audio quality in 60 seconds with this free setting...',
    example: 'Fix your audio background noise in 60 seconds with this free setting...',
    whyItWorks: 'High pain, immediate free solution.',
  },
  {
    id: 'hook-ex-19',
    category: 'relatable',
    title: 'The Confession',
    template: 'I spent 6 months trying [Method] and it completely failed...',
    example: 'I spent 6 months trying complex intros and it completely failed...',
    whyItWorks: 'Humbling experience shares warning.',
  },
  {
    id: 'hook-ex-20',
    category: 'secret',
    title: 'The Hidden Goldmine',
    template: 'The most underrated strategy for [Topic] in 2026...',
    example: 'The most underrated strategy for short-form video reach in 2026...',
    whyItWorks: 'Unexploited opportunity.',
  },
  {
    id: 'hook-ex-21',
    category: 'curiosity',
    title: 'The Shocking Discovery',
    template: 'I tested 50 video hooks. Here is the 1 format that beat all others...',
    example: 'I tested 50 video hooks. Here is the 1 format that beat all others...',
    whyItWorks: 'Data-driven proof comparison.',
  },
  {
    id: 'hook-ex-22',
    category: 'wish_i_knew',
    title: 'The Hard Truth',
    template: 'Wish I knew that [Common Belief] was actually holding me back...',
    example: 'Wish I knew that long intros were actually holding my channel back...',
    whyItWorks: 'Removes invisible handbrakes.',
  },
  {
    id: 'hook-ex-23',
    category: 'shortcut',
    title: 'The Rapid Blueprint',
    template: 'Copy my exact 15-second scripting layout for short videos...',
    example: 'Copy my exact 15-second scripting layout for viral short videos...',
    whyItWorks: 'Plug and play format.',
  },
  {
    id: 'hook-ex-24',
    category: 'mistake',
    title: 'The Audience Repellent',
    template: 'Saying this line in your first 3 seconds makes viewers leave instantly...',
    example: 'Saying "Hey guys welcome back" in your first 3 seconds makes viewers leave instantly...',
    whyItWorks: 'Identifies specific bad phrase to avoid.',
  },
  {
    id: 'hook-ex-25',
    category: 'pattern_interrupt',
    title: 'The Attention Grabber',
    template: 'Look at this! If you want [Goal], you need to know this...',
    example: 'Look at this! If you want higher video retention, you need to know this...',
    whyItWorks: 'Visual & verbal anchor combo.',
  },
  {
    id: 'hook-ex-26',
    category: 'controversy',
    title: 'The Trend Warning',
    template: 'Why following [Trend] is actually hurting your brand account...',
    example: 'Why following random lip-sync trends is actually hurting your account...',
    whyItWorks: 'Strategic caution message.',
  },
  {
    id: 'hook-ex-27',
    category: 'secret',
    title: 'The Secret Hook Formula',
    template: 'The 3-part hook formula that keeps 80% of viewers watching until the end...',
    example: 'The 3-part hook formula that keeps 80% of viewers watching until the end...',
    whyItWorks: 'Massive retention retention claim.',
  },
  {
    id: 'hook-ex-28',
    category: 'relatable',
    title: 'The Real Reason',
    template: 'We all hate [Annoying Task], so here is how to skip it forever...',
    example: 'We all hate writing script outlines, so here is how to skip it forever...',
    whyItWorks: 'Relieves creative friction.',
  },
  {
    id: 'hook-ex-29',
    category: 'shortcut',
    title: 'The Ultimate Hack',
    template: 'How to make 10 short videos in 1 hour using this method...',
    example: 'How to make 10 short videos in 1 hour using this batching method...',
    whyItWorks: 'Extreme batching efficiency.',
  },
  {
    id: 'hook-ex-30',
    category: 'wish_i_knew',
    title: 'The Final Advice',
    template: 'If you remember only one piece of advice about [Topic], make it this...',
    example: 'If you remember only one piece of advice about video hooks, make it this...',
    whyItWorks: 'High concentration of value.',
  },
];

/**
 * Utility to shuffle and retrieve N customized hook suggestions for a topic/industry.
 */
export function getRandomHookSuggestions(topicOrTitle: string, count: number = 6): HookTemplate[] {
  // Shuffle array using Fisher-Yates
  const array = [...VIRAL_HOOK_LIBRARY];
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }

  // Extract key topic or fallback to [your topic]
  const isGeneric = !topicOrTitle || ['tech', 'fitness', 'finance', 'real estate', 'gaming', 'e-commerce', 'fashion', 'general'].includes(topicOrTitle.toLowerCase().trim());
  const cleanTopic = (!isGeneric && topicOrTitle.trim().length > 2) ? topicOrTitle.trim() : '[your topic]';

  return array.slice(0, count).map((item) => {
    // Dynamically personalize placeholders if template has [Topic] or similar
    const personalizedExample = item.example
      .replace(/\[Topic\]|\[Topic\/Industry\]|\[Industry\]|\[Industry\/Creators\]/gi, cleanTopic)
      .replace(/\btech\b|\bfitness\b|\bfinance\b|\breal estate\b/gi, cleanTopic);
    return {
      ...item,
      example: personalizedExample,
    };
  });
}
